name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    # 1. Menjalankan MLflow Project (Re-training Otomatis)
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --entry-point main --env-manager local

    # 2. Menyimpan Artefak Model ke Repositori (Syarat Level Skilled - 3 pts)
    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: MLProject/mlruns/

    # 3. Membuat Docker Image Otomatis menggunakan mlflow build-docker (Syarat Level Advance - 4 pts)
    - name: Build Docker Image from MLflow Model
      env:
        # Mengizinkan MLflow membaca backend berbasis file store/folder biasa
        MLFLOW_ALLOW_FILE_STORE: "true"
      run: |
        # Memanggil file python eksternal untuk mendapatkan Run ID dengan aman
        LATEST_RUN_ID=$(python MLProject/get_run_id.py)
        echo "Menggunakan Run ID terbaru hasil training: $LATEST_RUN_ID"
        
        # Ekspor variabel lingkungan untuk tracking URI
        export MLFLOW_TRACKING_URI="MLProject/mlruns"
        
        # Menjalankan perintah build-docker menggunakan skema URI mlflow langsung
        mlflow models build-docker -m "runs:/$LATEST_RUN_ID/model" -n "nerosuprobo/workflow-ci-model:latest"