name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    - name: Run MLflow Project
      run: |
        mlflow run ./MLProject --entry-point main --env-manager local

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: mlruns/